language: perl

sudo: false

perl:
    - "5.26"
    
addons:
    apt:
        packages:
            - gzip

install:
    - "cpanm --quiet --notest Path::Tiny SemVer"
    - "wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.9.0/ncbi-blast-2.9.0+-x64-linux.tar.gz"
    - "tar zxvf ncbi-blast-2.9.0+-x64-linux.tar.gz"
    - "export PATH=$PWD/bin:$PWD/ncbi-blast-2.9.0+/bin:$PATH"

script:
    - "perl-biotool --version"
    - "perl-biotool --help"
