language: perl

sudo: false

perl:
    - "5.26"
    
addons:
    apt:
        packages:
            - gzip

install:
    - "cpanm --quiet --notest File::Which"
    - "export PATH=$PWD/bin:$PATH"

script:
    - "perl-biotool --version"
    - "perl-biotool --help"
    - "perl-biotool --check"
